### ISSUE TITLE
Two crashes on Android 7.0

### ISSUE THREAD

**Issue by ghost** [naturenet/naturenet-android-app#55] opened 2016-09-04 22:06 UTC
Crashed when trying to login
Crashed when click on Explore 
Device: Nexus 5X with Android 7.0

**Comment by WildWeazel** [comment] 2016-09-06 20:50
This was ultimately because of someone using an outdated version of the iOS app that submitted data in the wrong format. I repaired the data, but the issue here is that the app needs to be more robust in reading objects from the database.

**Comment by WildWeazel** [comment] 2016-09-14 16:55
I believe the root cause of these particular crashes has been resolved via database maintenance and work on #56

**Closed as completed by WildWeazel** 2016-09-14 16:55 UTC
Labels: bug, student
